namespace Athkar.Shareds.Enums;

/// <summary>What the app filters and styles an inbox row on.</summary>
public enum NotificationKind
{
    /// <summary>A scheduled adhkar reminder.</summary>
    Reminder = 1,

    /// <summary>A one-off message an admin composed.</summary>
    Broadcast = 2,

    /// <summary>Generated by the system — new content available, a reply to a suggestion.</summary>
    System = 3,
}
