"""Writes app/athkar_app/lib/core/surah_names.dart from data/surahs.json.

The listening tab needs the 114 surah names on a phone that has never
downloaded the mushaf, so they cannot come from the mushaf package. They are
not typed by hand either: this reads the metadata `pull.py` saved from the
canonical source (quran.com, via the quran.ai MCP server), and a regenerated
file is the only way the Dart list is allowed to change.

    python tools/quran-mcp/gen_surah_names.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "data", "surahs.json")
TARGET = os.path.join(HERE, "..", "..", "app", "athkar_app", "lib", "core", "surah_names.dart")


def dart(text: str) -> str:
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main() -> None:
    with open(SOURCE, encoding="utf-8") as handle:
        surahs = json.load(handle)

    if len(surahs) != 114 or [s["number"] for s in surahs] != list(range(1, 115)):
        raise SystemExit("surahs.json is not the 114 surahs in order; re-run pull.py")

    lines = [
        "// GENERATED by tools/quran-mcp/gen_surah_names.py from data/surahs.json",
        "// (quran.com metadata, pulled through the quran.ai MCP server). Do not",
        "// edit by hand — regenerate.",
        "",
        "/// One surah's name and length, for screens that must work without the",
        "/// mushaf package: the listening tab's surah list, above all.",
        "class SurahName {",
        "  const SurahName(this.number, this.arabic, this.english, this.verses, this.meccan);",
        "",
        "  final int number;",
        "  final String arabic;",
        "  final String english;",
        "  final int verses;",
        "  final bool meccan;",
        "}",
        "",
        "/// The 114 surahs, index 0 being al-Fatiha.",
        "const surahNames = <SurahName>[",
    ]

    for s in surahs:
        lines.append(
            f"  SurahName({s['number']}, {dart(s['name_arabic'])}, {dart(s['name_simple'])}, "
            f"{s['verses_count']}, {'true' if s['revelation_place'] == 'makkah' else 'false'}),"
        )

    lines += [
        "];",
        "",
        "/// The surah numbered [number], or null outside 1–114.",
        "SurahName? surahName(int number) =>",
        "    number >= 1 && number <= surahNames.length ? surahNames[number - 1] : null;",
        "",
    ]

    with open(TARGET, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))

    print(f"wrote {os.path.relpath(TARGET)} ({len(surahs)} surahs)")


if __name__ == "__main__":
    main()
